services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    # Listener / Hooks
    Pdir\ContaoWebtoolsBundle\EventListener\BackendMenuListener:
        public: true

    Pdir\ContaoWebtoolsBundle\EventListener\GeneratePageListener:
        public: true

    Pdir\ContaoWebtoolsBundle\EventListener\DataContainer\BackendUsabilityListener:
        public: true
